services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn la_paca.wsgi:application
    staticPublishPath: staticfiles